# -*- coding: utf-8 -*-
"""VoltRelay_Data_Analytics_Hackathon_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19JQKn1cqZhC2QjPi1gr1kNx7Fmy9KTXl
"""

import zipfile
import os

zip_path = "/content/DA_Project_Data-20260926T043523Z-1-001.zip"
extract_path = "/content/DA_Project_Data"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Files extracted successfully!")
print(os.listdir(extract_path))

import os

print(os.listdir("/content"))

import os

print(os.listdir("/content/DA_Project_Data"))

import os

print(os.listdir("/content/DA_Project_Data/DA_Project_Data"))

import pandas as pd

data_path = "/content/DA_Project_Data/DA_Project_Data"

swap_events = pd.read_csv(
    f"{data_path}/swap_events.csv"
)

print("Rows:", len(swap_events))
print("Columns:", len(swap_events.columns))

swap_events.head()

for i, col in enumerate(swap_events.columns, 1):
    print(i, "→", col)

missing = swap_events.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)b$0

print(swap_events["event_type"].value_counts(dropna=False))

missing_by_event = swap_events.groupby("event_type")[
    ["battery_out_id", "energy_to_recharge_kwh",
     "soh_out_pct", "soc_out_pct"]
].apply(lambda x: x.isnull().sum())

print(missing_by_event)

missing_by_event = swap_events.groupby("event_type")[
    ["battery_in_id", "soc_in_pct",
     "soh_in_pct", "km_since_last_swap"]
].apply(lambda x: x.isnull().sum())

print(missing_by_event)

print("Duplicate rows:", swap_events.duplicated().sum())

print("Duplicate event IDs:", swap_events["event_id"].duplicated().sum())

print(swap_events.dtypes)

swap_events["event_ts"] = pd.to_datetime(swap_events["event_ts"])

print(swap_events["event_ts"].dtype)

print("Negative queue wait:", (swap_events["queue_wait_sec"] < 0).sum())
print("Negative km:", (swap_events["km_since_last_swap"] < 0).sum())
print("SOC below 0:", (swap_events["soc_in_pct"] < 0).sum())
print("SOC above 100:", (swap_events["soc_in_pct"] > 100).sum())
print("SOH below 0:", (swap_events["soh_in_pct"] < 0).sum())
print("SOH above 100:", (swap_events["soh_in_pct"] > 100).sum())

print(
    swap_events.loc[
        swap_events["km_since_last_swap"] < 0,
        ["event_id", "rider_id", "event_ts", "event_type", "km_since_last_swap"]
    ].head(10)
)

print(
    swap_events.loc[
        swap_events["soh_in_pct"] > 100,
        ["event_id", "rider_id", "event_ts", "event_type", "soh_in_pct"]
    ].head(10)
)

print("Start date:", swap_events["event_ts"].min())
print("End date:", swap_events["event_ts"].max())

swap_events["date"] = swap_events["event_ts"].dt.date
swap_events["year_month"] = swap_events["event_ts"].dt.to_period("M").astype(str)
swap_events["hour"] = swap_events["event_ts"].dt.hour

print(swap_events[["event_ts", "date", "year_month", "hour"]].head())

total_attempts = len(swap_events)

completed_swaps = (
    swap_events["event_type"] == "swap_completed"
).sum()

unsuccessful_attempts = total_attempts - completed_swaps

completion_rate = completed_swaps / total_attempts * 100
failure_rate = unsuccessful_attempts / total_attempts * 100

print("Total attempts:", total_attempts)
print("Completed swaps:", completed_swaps)
print("Unsuccessful attempts:", unsuccessful_attempts)
print("Completion rate:", round(completion_rate, 2), "%")
print("Failure rate:", round(failure_rate, 2), "%")

monthly_performance = (
    swap_events.groupby("year_month")
    .agg(
        total_attempts=("event_id", "count"),
        completed_swaps=("event_type", lambda x: (x == "swap_completed").sum())
    )
    .reset_index()
)

monthly_performance["completion_rate"] = (
    monthly_performance["completed_swaps"]
    / monthly_performance["total_attempts"]
    * 100
)

monthly_performance["failure_rate"] = (
    100 - monthly_performance["completion_rate"]
)

monthly_performance

failure_breakdown = (
    swap_events["event_type"]
    .value_counts()
    .reset_index()
)

failure_breakdown.columns = ["event_type", "count"]

failure_breakdown

station_performance = (
    swap_events.groupby("station_id")
    .agg(
        total_attempts=("event_id", "count"),
        completed_swaps=("event_type", lambda x: (x == "swap_completed").sum())
    )
    .reset_index()
)

station_performance["failure_rate"] = (
    1 - station_performance["completed_swaps"]
    / station_performance["total_attempts"]
) * 100

station_performance = station_performance.sort_values(
    "failure_rate",
    ascending=False
)

station_performance.head(10)

stations = pd.read_csv(
    f"{data_path}/stations.csv"
)

print("Rows:", len(stations))
print("Columns:", len(stations.columns))

stations.head()

station_analysis = station_performance.merge(
    stations,
    on="station_id",
    how="left"
)

station_analysis.head()

city_performance = (
    station_analysis.groupby("city")
    .agg(
        total_attempts=("total_attempts", "sum"),
        completed_swaps=("completed_swaps", "sum")
    )
    .reset_index()
)

city_performance["failure_rate"] = (
    1 - city_performance["completed_swaps"]
    / city_performance["total_attempts"]
) * 100

city_performance = city_performance.sort_values(
    "failure_rate",
    ascending=False
)

city_performance

swap_city = swap_events.merge(
    stations[["station_id", "city"]],
    on="station_id",
    how="left"
)

city_failure_types = (
    swap_city[
        swap_city["event_type"] != "swap_completed"
    ]
    .groupby(["city", "event_type"])
    .size()
    .reset_index(name="count")
)

city_failure_types

queue_analysis = (
    swap_events.groupby("event_type")
    .agg(
        attempts=("event_id", "count"),
        avg_queue_wait_sec=("queue_wait_sec", "mean"),
        median_queue_wait_sec=("queue_wait_sec", "median")
    )
    .reset_index()
)

queue_analysis

hourly_queue = (
    swap_events.groupby("hour")
    .agg(
        total_attempts=("event_id", "count"),
        abandoned_queue=("event_type", lambda x: (x == "abandoned_queue").sum())
    )
    .reset_index()
)

hourly_queue["abandonment_rate"] = (
    hourly_queue["abandoned_queue"]
    / hourly_queue["total_attempts"]
    * 100
)

hourly_queue

station_type_analysis = (
    station_analysis.groupby("location_type")
    .agg(
        total_attempts=("total_attempts", "sum"),
        completed_swaps=("completed_swaps", "sum"),
        avg_failure_rate=("failure_rate", "mean")
    )
    .reset_index()
)

station_type_analysis["failure_rate"] = (
    1 -
    station_type_analysis["completed_swaps"]
    / station_type_analysis["total_attempts"]
) * 100

station_type_analysis.sort_values("failure_rate", ascending=False)

battery_failure_by_city = (
    swap_city.groupby("city")
    .agg(
        total_attempts=("event_id", "count"),
        no_charged_battery_failures=(
            "event_type",
            lambda x: (x == "failed_no_charged_battery").sum()
        )
    )
    .reset_index()
)

battery_failure_by_city["battery_failure_rate"] = (
    battery_failure_by_city["no_charged_battery_failures"]
    / battery_failure_by_city["total_attempts"]
    * 100
)

battery_failure_by_city.sort_values(
    "battery_failure_rate",
    ascending=False
)

completed_battery_health = swap_events[
    swap_events["event_type"] == "swap_completed"
].copy()

battery_health_summary = completed_battery_health[
    ["soh_in_pct", "soh_out_pct"]
].describe()

battery_health_summary

swap_events["soh_band"] = pd.cut(
    swap_events["soh_in_pct"],
    bins=[0, 70, 80, 90, 100, 110],
    labels=["<70%", "70-80%", "80-90%", "90-100%", ">100%"]
)

soh_failure_analysis = (
    swap_events.groupby("soh_band", observed=False)
    .agg(
        total_attempts=("event_id", "count"),
        completed_swaps=("event_type", lambda x: (x == "swap_completed").sum())
    )
    .reset_index()
)

soh_failure_analysis["failure_rate"] = (
    1 -
    soh_failure_analysis["completed_swaps"]
    / soh_failure_analysis["total_attempts"]
) * 100

soh_failure_analysis

batteries = pd.read_csv(
    f"{data_path}/batteries.csv"
)

print("Rows:", len(batteries))
print("Columns:", len(batteries.columns))

batteries.head()

supplier_health = (
    batteries.groupby("supplier")
    .agg(
        battery_count=("battery_id", "count"),
        avg_initial_soh=("initial_soh_pct", "mean"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

supplier_health

lot_health = (
    batteries.groupby(["supplier", "manufacturing_lot"])
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

lot_health.sort_values(
    "avg_current_soh",
    ascending=True
).head(15)

retirement_analysis = (
    batteries.groupby("retirement_reason", dropna=False)
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

retirement_analysis

batteries.columns.tolist()

batteries["manufacture_date"] = pd.to_datetime(batteries["manufacture_date"])
batteries["commission_date"] = pd.to_datetime(batteries["commission_date"])

analysis_date = pd.Timestamp("2025-06-30")

batteries["age_days"] = (
    analysis_date - batteries["commission_date"]
).dt.days

batteries[["battery_id", "commission_date", "current_soh_pct", "age_days"]].head()

batteries["age_group"] = pd.cut(
    batteries["age_days"],
    bins=[0, 180, 360, 540, 720, 900, float("inf")],
    labels=["0-6 months", "6-12 months", "12-18 months",
            "18-24 months", "24-30 months", "30+ months"]
)

age_soh_analysis = (
    batteries.groupby("age_group", observed=False)
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

age_soh_analysis

supplier_age_soh = (
    batteries.groupby(["supplier", "age_group"], observed=False)
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

supplier_age_soh

supplier_retirement = (
    batteries.groupby(["supplier", "retirement_reason"], dropna=False)
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean")
    )
    .reset_index()
)

supplier_retirement

kyron_lot_analysis = (
    batteries[batteries["supplier"] == "Kyron"]
    .groupby("manufacturing_lot")
    .agg(
        battery_count=("battery_id", "count"),
        avg_current_soh=("current_soh_pct", "mean"),
        end_of_life=("retirement_reason", lambda x: (x == "end_of_life").sum())
    )
    .reset_index()
    .sort_values("avg_current_soh")
)

kyron_lot_analysis

swap_events[["battery_in_id", "battery_out_id"]].head()

battery_soh = batteries[["battery_id", "current_soh_pct"]].copy()

swap_battery_analysis = swap_events.merge(
    battery_soh,
    left_on="battery_in_id",
    right_on="battery_id",
    how="left"
)

swap_battery_analysis[["battery_in_id", "current_soh_pct", "event_type"]].head()

swap_battery_analysis["soh_band"] = pd.cut(
    swap_battery_analysis["current_soh_pct"],
    bins=[0, 70, 80, 90, 100, 110],
    labels=["<70%", "70-80%", "80-90%", "90-100%", ">100%"]
)

battery_soh_failure = (
    swap_battery_analysis.groupby("soh_band", observed=False)
    .agg(
        total_attempts=("event_id", "count"),
        completed_swaps=("event_type", lambda x: (x == "swap_completed").sum())
    )
    .reset_index()
)

battery_soh_failure["failure_rate"] = (
    1 - battery_soh_failure["completed_swaps"]
    / battery_soh_failure["total_attempts"]
) * 100

battery_soh_failure

soh_failure_type = (
    swap_events.groupby(["soh_band", "event_type"], observed=False)
    .size()
    .reset_index(name="count")
)

soh_failure_type

high_failure_stations = station_analysis[
    station_analysis["failure_rate"] > 8
]

high_failure_stations.groupby("city").agg(
    station_count=("station_id", "count"),
    avg_failure_rate=("failure_rate", "mean"),
    total_attempts=("total_attempts", "sum")
).reset_index().sort_values(
    "avg_failure_rate",
    ascending=False
)

high_failure_station_ids = high_failure_stations["station_id"].tolist()

high_station_failures = (
    swap_events[swap_events["station_id"].isin(high_failure_station_ids)]
    .groupby("event_type")
    .size()
    .reset_index(name="count")
)

high_station_failures

revenue_analysis = (
    swap_events.groupby("event_type")
    .agg(
        attempts=("event_id", "count"),
        total_amount=("amount_charged_inr", "sum"),
        avg_amount=("amount_charged_inr", "mean")
    )
    .reset_index()
)

revenue_analysis

city_revenue = (
    swap_city.groupby("city")
    .agg(
        total_attempts=("event_id", "count"),
        completed_swaps=("event_type", lambda x: (x == "swap_completed").sum()),
        total_revenue=("amount_charged_inr", "sum")
    )
    .reset_index()
)

city_revenue["failure_rate"] = (
    1 - city_revenue["completed_swaps"] / city_revenue["total_attempts"]
) * 100

city_revenue.sort_values("total_revenue", ascending=False)

city_revenue["avg_revenue_per_completed_swap"] = (
    city_revenue["total_revenue"] /
    city_revenue["completed_swaps"]
)

city_revenue[
    ["city", "completed_swaps", "total_revenue",
     "avg_revenue_per_completed_swap"]
].sort_values(
    "avg_revenue_per_completed_swap",
    ascending=False
)

overall_avg_revenue = (
    swap_events.loc[
        swap_events["event_type"] == "swap_completed",
        "amount_charged_inr"
    ].mean()
)

total_attempts = len(swap_events)

one_percent_additional_swaps = total_attempts * 0.01

revenue_opportunity_1pct = (
    one_percent_additional_swaps * overall_avg_revenue
)

overall_avg_revenue, one_percent_additional_swaps, revenue_opportunity_1pct